# Challenge 1

In [5]:
import numpy as np

In [35]:
matriz_a = np.zeros([4,4])

In [36]:
matriz_a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
matriz_a[0,1] = 1
matriz_a[0,2] = 1
matriz_a[0,3] = 1
matriz_a[1,0] = 1
matriz_a[2,0] = 1
matriz_a[2,2] = 1
matriz_a[1,2] = 1
matriz_a[3,1] = 1
matriz_a[3,2] = 1
matriz_a[3,3] = 1

In [38]:
matriz_a.T

array([[0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.],
       [1., 0., 0., 1.]])

In [39]:
matriz_d = np.zeros([4,4])
matriz_j = np.zeros([4,4])

In [40]:
matriz_d[0,0] = 1
matriz_d[0,1] = 1
matriz_d[0,2] = 1
matriz_d[1,3] = 1
matriz_d[2,3] = 1
matriz_d[3,2] = 1
matriz_d[3,1] = 1
matriz_d[3,0] = 1
matriz_d[2,0] = 1
matriz_d[1,0] = 1

In [41]:
matriz_d

array([[1., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 0.]])

In [42]:
matriz_j[0,0] = 1
matriz_j[0,1] = 1
matriz_j[0,2] = 1
matriz_j[0,3] = 1
matriz_j[1,2] = 1
matriz_j[2,2] = 1
matriz_j[3,2] = 1
matriz_j[3,1] = 1
matriz_j[3,0] = 1
matriz_j[2,0] = 1

In [43]:
matriz_j

array([[1., 1., 1., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.]])

In [44]:
matrz = np.zeros([4,4])

In [57]:
matrz[1:3,1] = 2

In [58]:
matrz

array([[0., 1., 1., 0.],
       [0., 2., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 0., 0.]])

# Challenge 2

In [59]:
n = 6
dama = [["01"[(i+j+n%2+1) % 2] for i in range(n)] for j in range(n)]

In [60]:
dama

[['1', '0', '1', '0', '1', '0'],
 ['0', '1', '0', '1', '0', '1'],
 ['1', '0', '1', '0', '1', '0'],
 ['0', '1', '0', '1', '0', '1'],
 ['1', '0', '1', '0', '1', '0'],
 ['0', '1', '0', '1', '0', '1']]